apiVersion: database.arangodb.com/v1alpha
kind: ArangoDeployment
metadata:
  name: dreamerdb
spec:
  mode: Single
  tls:
    caSecretName: None
  auth:
    jwtSecretName: None
  externalAccess:
    type: None
